plugins {
    kotlin("jvm") version "1.9.24" apply false

    // Android Plugins
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.kotlinAndroid) apply false
    id("com.google.devtools.ksp") version "2.3.4" apply false
}

allprojects {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    buildscript {
        repositories {
            google()
            mavenCentral()
            // r8:9.0.32 は google() または mavenCentral() にあります
        }
        dependencies {
            // R8を最新バージョン(9.0.28以降がKotlin 2.3対応)に強制
            classpath("com.android.tools:r8:9.0.32")
        }
    }
}

tasks.register("applyPatch") {
    group = "tools"
    description = "Applies a multi-file patch generated by Gemini (Repomix format)."

    // 1. 構成フェーズで必要なパスを java.io.File (シリアライズ可能) として確定させる
    // これにより doLast 内で project や layout オブジェクトを参照しなくて済むようにする
    val rootDir = layout.projectDirectory.asFile
    val patchFile = layout.projectDirectory.file("repomix-patch.txt").asFile

    doLast {
        // 2. 実行フェーズ (Configuration Cache に保存される部分)

        if (!patchFile.exists()) {
            throw GradleException("Patch file not found: ${patchFile.absolutePath}\nPlease create 'patch.txt' in the project root.")
        }

        println("Applying patch from: ${patchFile.name}")

        val fileHeaderPattern = Regex("^File:\\s+(.+)$")
        var currentFile: java.io.File? = null
        val contentBuffer = StringBuilder()

        // 3. ヘルパー関数を doLast の内部関数として定義し、Scriptオブジェクトへの参照を切る
        fun writeContent(file: java.io.File, content: String) {
            file.parentFile.mkdirs()
            file.writeText(content)
            println("✅ Updated: ${file.path}")
        }

        patchFile.forEachLine { line ->
            val match = fileHeaderPattern.find(line)
            if (match != null) {
                // 前のファイルがあれば書き込む
                currentFile?.let { file ->
                    writeContent(file, contentBuffer.toString())
                    contentBuffer.clear()
                }

                // 新しいファイルのパスを解決 (rootDir を基点にする)
                val relativePath = match.groupValues[1].trim()
                currentFile = rootDir.resolve(relativePath)
                println("Targeting: $relativePath")
            } else {
                // ファイルパスが見つかるまではバッファしない
                if (currentFile != null) {
                    contentBuffer.append(line).append("\n")
                }
            }
        }

        // 最後のファイルを書き込む
        currentFile?.let { file ->
            writeContent(file, contentBuffer.toString())
        }
    }
}

tasks.register<Copy>("copyProjectResourcesToCore") {
    group = "distribution"
    description = "Copies resources from subprojects to TestBed Core resources."

    val coreResourcesDir = file("${rootProject.projectDir}/../testbed-core/composeApp/resources")
    into(coreResourcesDir)

    subprojects.forEach { project ->
        val resDir = project.file("resources")
        if (resDir.exists() && resDir.isDirectory) {
            from(resDir)
        }
    }
}

tasks.register<Zip>("zipPluginsAndResources") {
    group = "distribution"
    description = "Zips plugins and resources produced by this project."

    // 最新のコードをassembleした結果を固めるため、サブプロジェクトのビルドおよびコピー生成タスクに依存させる
    dependsOn(subprojects.flatMap { project ->
        project.tasks.matching { task ->
            task.name == "assemble" ||
            task.name == "copyApkToCore" ||
            task.name == "generateAndDeployTestApks"
        }
    })
    dependsOn("copyProjectResourcesToCore")

    val corePluginsDir = file("${rootProject.projectDir}/../testbed-core/composeApp/plugins")
    val coreResourcesDir = file("${rootProject.projectDir}/../testbed-core/composeApp/resources")

    // pluginsディレクトリを含める
    from(corePluginsDir) {
        into("plugins")
    }

    // resourcesディレクトリを含める。ただし、このプロジェクトの成果物ではない mutton-agent.apk は除外する
    from(coreResourcesDir) {
        into("resources")
        exclude("mutton-agent.apk")
    }

    archiveFileName.set("plugins-and-resources.zip")
    destinationDirectory.set(layout.buildDirectory.dir("distributions"))

    doLast {
        println("✅ Zip file created at: ${archiveFile.get().asFile.absolutePath}")
    }
}

